services:
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:2026.8.2
    container_name: home-assistant
    network_mode: host
    restart: unless-stopped
    mem_limit: 1024m
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - TZ=${TZ:-Africa/Johannesburg}
    volumes:
      - /DATA/AppData/home-assistant/config:/config
