services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.11
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "${JELLYFIN_PORT:-8096}:8096"
    environment:
      - TZ=${TZ:-Africa/Johannesburg}
    volumes:
      - /DATA/AppData/jellyfin/config:/config
      - /DATA/AppData/jellyfin/cache:/cache
      - /DATA/AppData/jellyfin/test-media:/testmedia:ro
      - /DATA/AppData/media-library/movies:/movies:ro
      - /DATA/AppData/media-library/tv:/tv:ro
      - /DATA/AppData/decypharr/mnt:/mnt:ro,rshared
    devices:
      - /dev/dri:/dev/dri
