services:
  caddy:
    image: caddy:2.11.4
    container_name: caddy
    restart: unless-stopped
    mem_limit: 128m
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "443:443"
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile:ro
      - /DATA/AppData/caddy/certs:/certs:ro
      - /DATA/AppData/caddy/data:/data
