services:
  radarr:
    image: lscr.io/linuxserver/radarr:6.3.0.10514-ls312
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Europe/London}
    volumes:
      - /DATA/AppData/radarr/config:/config
      - /DATA/AppData/decypharr/downloads:/downloads
      - /DATA/AppData/decypharr/mnt:/mnt:rshared
      - /DATA/AppData/media-library/movies:/movies
    ports:
      - "${RADARR_PORT:-7878}:7878"
