services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.5.2
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Europe/London}
    volumes:
      - /DATA/AppData/prowlarr/config:/config
    ports:
      - "${PROWLARR_PORT:-9696}:9696"
